services:
  db:
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: local_db
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"